name: Build and Deploy
on: # ç›‘å¬ main åˆ†æ”¯ä¸Šçš„ push äº‹ä»¶
  push:
    branches:
      - new-design
jobs:
  build:
    runs-on: ubuntu-latest # æ„å»ºç¯å¢ƒä½¿ç”¨ ubuntu
    steps:
      - name: Checkout  # å°†ä»£ç æ‹‰åˆ°è™šæ‹Ÿæœº
        uses: actions/checkout@v2.3.1  
        with:
          persist-credentials: false

        # å®‰è£…ä¾èµ–
      - name: npm Install 
        run: npm install 
        # æ‰“åŒ…é¡¹ç›®
      - name: npm Build 
        run: npm run build  
        
      - name: Deploy ğŸš€ # éƒ¨ç½²
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{secrets.HOST}}
          user: ${{secrets.USERNAME}}
          pass: ${{secrets.PASSWORD}}
          post: ${{secrets.PORT}}
          local: './dist'
          remote: /www/wwwroot/120.48.31.206
